dist: bionic
language: node_js

install:
    - npm install
    - npm run build
before_deploy:
    - ssh-keyscan -H $HOSTGATOR_HOST >> ~/.ssh/known_hosts
    
deploy:
    - sync -avce ssh --delete ./dist/ $HOSTGATOR_USER@$HOSTGATOR_HOST:$HOSTGATOR_WORKING_DIRECTORY